version: '3.8'

services:
  scripture-scramble:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: db-server
    ports:
      - "3001:3001"
    restart: unless-stopped
    volumes:
      - ./data:/usr/src/app/data
    environment:
      - NODE_ENV=production
